blog/urls.py
from django.urls import path

from blog.views import BlogListView, BlogDetailView, CommentView

app_name = 'blog'

urlpatterns = [

    path('<int:pk>/comment-create/', CommentView.as_view(), name='comment-create'),
    path('', BlogListView.as_view(), name='blog-list'),
    path('<int:pk>/', BlogDetailView.as_view(), name='blog-detail'),

]

home/urls.py
from django.urls import path

from home.views import HomeTemplateView, AboutTemplateView

app_name = 'home'

urlpatterns = [
    path('', HomeTemplateView.as_view(), name='home'),
    path('about/', AboutTemplateView.as_view(), name='about'),
]

mainsettings/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

urlpatterns += i18n_patterns(
    path('accounts/', include('registration.backends.default.urls')),
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('shop/', include('shop.urls', namespace='shop')),
    path('watch/', include('watches.urls', namespace='watch')),
    path('mobile/', include('mobile.urls', namespace='mobile')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('wishlist/', include('wishlist.urls', namespace='wishlist')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('checkout/', include('checkouts.urls', namespace='checkout')),
    path('user/', include('users.urls', namespace='profile')),
)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mobile/urls.py
from django.urls import path

from mobile.views import MobileListView, MobileDetailView

app_name = 'mobile'

urlpatterns = [
    path('', MobileListView.as_view(), name='mobile-list'),
    path('<int:pk>/', MobileDetailView.as_view(), name='mobile-view'),
]

shop/urls.py
from django.urls import path

from shop.views import ShopListView, ProductsDetailView

app_name = 'shop'

urlpatterns = [
    path('', ShopListView.as_view(), name='shop-list'),
    path('<int:pk>/', ProductsDetailView.as_view(), name='detail-view'),
]

users/urls.py
from django.urls import path

from users.views import UserProfileUpdateView

app_name = 'profile'

urlpatterns = [
    path('', UserProfileUpdateView.as_view(), name='user')
]

templates/layouts/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% trans 'Khalim Brand' %}</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'images/favicon.png' %}">
    <link rel="stylesheet" href="{% static 'css/material-design-iconic-font.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/fontawesome-stars.css' %}">
    <link rel="stylesheet" href="{% static 'css/meanmenu.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/slick.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/venobox.css' %}">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/helper.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
    <script src="{% static 'js/vendor/modernizr-2.8.3.min.js' %}"></script>
    {% block extra_css %}

    {% endblock %}
</head>
<body>

<div class="body-wrapper">

{% include 'layouts/header.html' %}

{% block content %}

{% endblock %}

{% include 'layouts/footer.html' %}

</div>

<script src="{% static 'js/vendor/jquery-1.12.4.min.js' %}"></script>
<script src="{% static 'js/vendor/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/ajax-mail.js' %}"></script>
<script src="{% static 'js/jquery.meanmenu.min.js' %}"></script>
<script src="{% static 'js/wow.min.js' %}"></script>
<script src="{% static 'js/slick.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/isotope.pkgd.min.js' %}"></script>
<script src="{% static 'js/imagesloaded.pkgd.min.js' %}"></script>
<script src="{% static 'js/jquery.mixitup.min.js' %}"></script>
<script src="{% static 'js/jquery.countdown.min.js' %}"></script>
<script src="{% static 'js/jquery.counterup.min.js' %}"></script>
<script src="{% static 'js/waypoints.min.js' %}"></script>
<script src="{% static 'js/jquery.barrating.min.js' %}"></script>
<script src="{% static 'js/jquery-ui.min.js' %}"></script>
<script src="{% static 'js/venobox.min.js' %}"></script>
<script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
<script src="{% static 'js/scrollUp.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
{% block extra_js %}

{% endblock %}
</body>
</html>

templates/layouts/footer.html
{% load static %}
{% load i18n %}

<div class="footer">
    <div class="footer-static-top">
        <div class="container">
            <div class="footer-shipping pt-60 pb-55 pb-xs-25">
                <div class="row">
                    <div class="col-lg-3 col-md-6 col-sm-6 pb-sm-55 pb-xs-55">
                        <div class="li-shipping-inner-box">
                            <div class="shipping-icon">
                                <img src="{% static 'images/shipping-icon/1.png' %}" alt="Shipping Icon">
                            </div>
                            <div class="shipping-text">
                                <h2>{% trans 'Free Delivery' %}</h2>
                                <p>{% trans 'And free returns. See checkout for delivery dates' %}.</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6 col-sm-6 pb-sm-55 pb-xs-55">
                        <div class="li-shipping-inner-box">
                            <div class="shipping-icon">
                                <img src="{% static 'images/shipping-icon/2.png' %}" alt="Shipping Icon">
                            </div>
                            <div class="shipping-text">
                                <h2>{% trans 'Safe Payment' %}</h2>
                                <p>{% trans "Pay with the world's most popular and secure payment methods" %}.</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6 col-sm-6 pb-xs-30">
                        <div class="li-shipping-inner-box">
                            <div class="shipping-icon">
                                <img src="{% static 'images/shipping-icon/3.png' %}" alt="Shipping Icon">
                            </div>
                            <div class="shipping-text">
                                <h2>{% trans 'Shop with Confidence' %}</h2>
                                <p>{% trans 'Our Buyer Protection covers your purchase from click to delivery' %}.</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6 col-sm-6 pb-xs-30">
                        <div class="li-shipping-inner-box">
                            <div class="shipping-icon">
                                <img src="{% static 'images/shipping-icon/4.png' %}" alt="Shipping Icon">
                            </div>
                            <div class="shipping-text">
                                <h2>24/7 {% trans 'Help Center' %}</h2>
                                <p>{% trans 'Have a question? Call a Specialist or chat online' %}.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-static-middle">
        <div class="container">
            <div class="footer-logo-wrap pt-50 pb-35">
                <div class="row">
                    <div class="col-lg-4 col-md-6">
                        <div class="footer-logo">
                            <img src="{% static 'images/menu/logo/1.jpg' %}" alt="Footer Logo">
                            <p class="info">
                                We are a team of designers and developers that create high quality HTML Template &
                                Woocommerce, Shopify Theme.
                            </p>
                        </div>
                        <ul class="des">
                            <li>
                                <span>Address: </span>
                                6688Princess Road, London, Greater London BAS 23JK, UK
                            </li>
                            <li>
                                <span>{% trans 'Phone' %}: </span>
                                <a href="#">(+123) 123 321 345</a>
                            </li>
                            <li>
                                <span>{% trans 'Email' %}: </span>
                                <a href="mailto://info@yourdomain.com">info@yourdomain.com</a>
                            </li>
                        </ul>
                    </div>
                    <div class="col-lg-2 col-md-3 col-sm-6">
                        <div class="footer-block">
                            <h3 class="footer-block-title">{% trans 'Product' %}</h3>
                            <ul>
                                <li><a href="#">{% trans 'Prices drop' %}</a></li>
                                <li><a href="#">{% trans 'New products' %}</a></li>
                                <li><a href="#">{% trans 'Best sales' %}</a></li>
                                <li><a href="#">{% trans 'Contact us' %}</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-2 col-md-3 col-sm-6">
                        <div class="footer-block">
                            <h3 class="footer-block-title">{% trans 'Our company' %}</h3>
                            <ul>
                                <li><a href="#">{% trans 'Delivery' %}</a></li>
                                <li><a href="#">{% trans 'Legal Notice' %}</a></li>
                                <li><a href="#">{% trans 'About us' %}</a></li>
                                <li><a href="#">{% trans 'Contact us' %}</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="footer-block">
                            <h3 class="footer-block-title">{% trans 'Follow Us' %}</h3>
                            <ul class="social-link">
                                <li class="twitter">
                                    <a href="https://twitter.com/" data-toggle="tooltip" target="_blank"
                                       title="Twitter">
                                        <i class="fa fa-twitter"></i>
                                    </a>
                                </li>
                                <li class="rss">
                                    <a href="https://rss.com/" data-toggle="tooltip" target="_blank" title="RSS">
                                        <i class="fa fa-rss"></i>
                                    </a>
                                </li>
                                <li class="google-plus">
                                    <a href="https://www.plus.google.com/discover" data-toggle="tooltip" target="_blank"
                                       title="Google +">
                                        <i class="fa fa-google-plus"></i>
                                    </a>
                                </li>
                                <li class="facebook">
                                    <a href="https://www.facebook.com/" data-toggle="tooltip" target="_blank"
                                       title="Facebook">
                                        <i class="fa fa-facebook"></i>
                                    </a>
                                </li>
                                <li class="youtube">
                                    <a href="https://www.youtube.com/" data-toggle="tooltip" target="_blank"
                                       title="Youtube">
                                        <i class="fa fa-youtube"></i>
                                    </a>
                                </li>
                                <li class="instagram">
                                    <a href="https://www.instagram.com/" data-toggle="tooltip" target="_blank"
                                       title="Instagram">
                                        <i class="fa fa-instagram"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>
                        <div class="footer-newsletter">
                            <h4>Sign up to newsletter</h4>
                            <form action="#" method="post" id="mc-embedded-subscribe-form"
                                  name="mc-embedded-subscribe-form" class="footer-subscribe-form validate"
                                  target="_blank" novalidate>
                                <div id="mc_embed_signup_scroll">
                                    <div id="mc-form" class="mc-form subscribe-form form-group">
                                        <input id="mc-email" type="email" autocomplete="off"
                                               placeholder="Enter your email"/>
                                        <button class="btn" id="mc-submit">{% trans 'Subscribe' %}</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-static-bottom pt-55 pb-55">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="footer-links">
                        <ul>
                            <li><a href="#">{% trans 'Online Shopping' %}</a></li>
                            <li><a href="#">{% trans 'Promotions' %}</a></li>
                            <li><a href="#">{% trans 'My Orders' %}</a></li>
                            <li><a href="#">{% trans 'Help' %}</a></li>
                            <li><a href="#">{% trans 'Customer Service' %}</a></li>
                            <li><a href="#">{% trans 'Support' %}</a></li>
                            <li><a href="#">{% trans 'Most Populars' %}</a></li>
                            <li><a href="#">{% trans 'New Arrivals' %}</a></li>
                            <li><a href="#">{% trans 'Special Products' %}</a></li>
                            <li><a href="#">{% trans 'Our Stores' %}</a></li>
                            <li><a href="#">{% trans 'Shipping' %}</a></li>
                            <li><a href="#">{% trans 'Payments' %}</a></li>
                            <li><a href="#">{% trans 'Checkout' %}</a></li>
                            <li><a href="#">{% trans 'Discount' %}</a></li>
                        </ul>
                    </div>
                    <div class="copyright text-center">
                        <a href="#">
                            <img src="{% static 'images/payment/1.png' %}" alt="">
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/layouts/header.html
{% load static %}
{% load basic_tags %}
{% load i18n %}
<header>
    <div class="header-top">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-4">
                    <div class="header-top-left">
                        <ul class="phone-wrap">
                            <li><span>{% trans 'Telephone Enquiry' %}:</span><a href="#">(+99894) 707 71 71</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-9 col-md-8">
                    <div class="header-top-right">
                        <ul class="ht-menu">
                            <li>
                                {% if request.user.is_authenticated %}
                                    <div class="ht-setting-trigger"><span>{% trans 'Log Out' %}</span></div>
                                {% else %}
                                    <div class="ht-setting-trigger"><span>{% trans 'Log In' %}</span></div>
                                {% endif %}
                                <div class="setting ht-setting">
                                    <ul class="ht-setting-list">
                                        {% if request.user.is_authenticated %}
                                            <li><a href="{% url 'auth_logout' %}"><strong style="color: #111111">
                                                {% trans 'Log Out' %}</strong></a></li>
                                        {% else %}
                                            <li><a href="{% url 'auth_login' %}"><strong style="color: #111111">
                                                {% trans 'Log In' %}</strong></a></li>
                                        {% endif %}
                                    </ul>
                                </div>
                            </li>
                            <li>
                                <a href="{% url 'profile:user' %}"><span
                                        style="color: #111111">{% trans 'Profile' %}</span></a>
                            </li>
                            <li>
                                <span class="language-selector-wrapper">{% trans 'Language' %} :</span>
                                {% get_current_language as lang %}
                                <div class="ht-language-trigger"><span>{{ lang }}</span></div>
                                <div class="language ht-language">
                                    <ul class="ht-setting-list">
                                        {% get_available_languages as all_langs %}
                                        {% for l in all_langs %}
                                            {% if l.0 != lang %}
                                                <li class="active"><a href="{% get_lang_url request l.0 %}">
                                                    <img src="{% static 'images/menu/flag-icon/1.jpg' %}"
                                                         alt="">{% trans 'English' %}</a></li>
                                                <li><a href="{% get_lang_url request l.0 %}">
                                                    <img src="{% static 'images/menu/flag-icon/uzb-2.png' %}"
                                                         alt="">{% trans 'Uzbek' %}</a>
                                                </li>
                                            {% endif %}
                                        {% endfor %}
                                    </ul>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="header-middle pl-sm-0 pr-sm-0 pl-xs-0 pr-xs-0">
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="logo pb-sm-30 pb-xs-30">
                        <a href="#">
                            <img src="{% static 'images/menu/logo/1.jpg' %}" alt="">
                        </a>
                    </div>
                </div>
                <div class="col-lg-9 pl-0 ml-sm-15 ml-xs-15">
                    <form action="{% url 'shop:shop-list' %}" class="hm-searchbox">
                        <input name="q" type="text" placeholder="Enter your search key ...">
                        <button class="li-btn" type="submit"><i class="fa fa-search"></i></button>
                    </form>
                    <div class="header-middle-right">
                        <ul class="hm-menu">
                            <li class="hm-wishlist">
                                <a href="{% url 'wishlist:user-wishlist' %}">
                                    <span class="cart-item-count wishlist-item-count">0</span>
                                    <i class="fa fa-heart-o"></i>
                                </a>
                            </li>
                            <li class="hm-minicart">
                                <div class="hm-minicart-trigger">
                                    <span class="item-icon"></span>
                                    <span class="item-text">£80.00
                                                    <span class="cart-item-count">2</span>
                                                </span>
                                </div>
                                <span></span>
                                <div class="minicart">
                                    <p class="minicart-total">{% trans 'SUBTOTAL' %}: <span>£80.00</span></p>
                                    <div class="minicart-button">
                                        <a href="{% url 'checkout:cart' %}"
                                           class="li-button li-button-fullwidth li-button-dark">
                                            <span>{% trans 'View Full Cart' %}</span>
                                        </a>
                                        <a href="{% url 'checkouts:checkouts' %}" class="li-button li-button-fullwidth">
                                            <span>{% trans 'Checkout' %}</span>
                                        </a>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="header-bottom header-sticky d-none d-lg-block d-xl-block">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="hb-menu">
                        <nav>
                            <ul>
                                <li class="dropdown-holder">
                                    <a href="{% url 'home:home' %}">{% trans 'Home' %}</a>
                                </li>
                                <li class="megamenu-holder">
                                    <a href="{% url 'shop:shop-list' %}">{% trans 'Shop' %}</a>
                                </li>
                                <li class="dropdown-holder">
                                    <a href="{% url 'watch:watch-list' %}">{% trans 'Watch' %}</a>
                                </li>
                                <li class="megamenu-static-holder">
                                    <a href="{% url 'mobile:mobile-list' %}">{% trans 'Mobile' %}</a>
                                </li>
                                <li>
                                    <a href="{% url 'home:about' %}">{% trans 'About Us' %}</a>
                                </li>
                                <li>
                                    <a href="{% url 'blog:blog-list' %}">{% trans 'Blog' %}</a>
                                </li>
                                <li>
                                    <a href="{% url 'contact:contact' %}">{% trans 'Contact' %}</a>
                                </li>
                                <li>
                                    <a href="{% url 'contact:faq' %}">{% trans 'FAQ' %}</a>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="mobile-menu-area d-lg-none d-xl-none col-12">
        <div class="container">
            <div class="row">
                <div class="mobile-menu">
                </div>
            </div>
        </div>
    </div>
</header>