blog/urls.py
from django.urls import path

from blog.views import BlogListView, BlogDetailView, CommentView

app_name = 'blog'

urlpatterns = [

    path('<int:pk>/comment-create/', CommentView.as_view(), name='comment-create'),
    path('', BlogListView.as_view(), name='blog-list'),
    path('<int:pk>/', BlogDetailView.as_view(), name='blog-detail'),

]

checkouts/urls.py
from django.urls import path

from checkouts.views import CheckoutTemplateView, CartTemplateView

app_name = 'checkouts'

urlpatterns = [
    path('', CheckoutTemplateView.as_view(), name='checkouts'),
    path('cart/', CartTemplateView.as_view(), name='cart'),
]

contact/urls.py
from django.urls import path

from contact.views import ContactCreateView, FaqView

app_name = 'contact'

urlpatterns = [
    path('', ContactCreateView.as_view(), name='contact'),
    path('faqs/', FaqView.as_view(), name='faq')

]

mobile/urls.py
from django.urls import path

from mobile.views import MobileListView, MobileDetailView

app_name = 'mobile'

urlpatterns = [
    path('', MobileListView.as_view(), name='mobile-list'),
    path('<int:pk>/', MobileDetailView.as_view(), name='mobile-view'),
]

shop/urls.py
from django.urls import path

from shop.views import ShopListView, ProductsDetailView

app_name = 'shop'

urlpatterns = [
    path('', ShopListView.as_view(), name='shop-list'),
    path('<int:pk>/', ProductsDetailView.as_view(), name='detail-view'),
]

watches/urls.py
from django.urls import path

from watches.views import WatchListView, WatchesDetailView

app_name = 'watch'

urlpatterns = [
    path('', WatchListView.as_view(), name='watch-list'),
    path('<int:pk>/', WatchesDetailView.as_view(), name='watch-view'),
]

wishlist/urls.py
from django.urls import path

from wishlist.views import WishListView, add_wishlist

app_name = 'wishlist'

urlpatterns = [
    path('', WishListView.as_view(), name='user-wishlist'),
    path('wishlist/<int:pk>/<str:klass>/', add_wishlist, name='add-wishlist'),
]

checkouts/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.utils.translation import gettext_lazy as _
# Create your models here.
from mobile.models import MobilePhone
from shop.models import Products
from watches.models import WatchModel

UserModel = get_user_model()


class CheckoutsModel(models.Model):
    user = models.ForeignKey(UserModel, related_name='orders', on_delete=models.CASCADE, verbose_name=_('user'))
    products = models.ManyToManyField(Products, related_name='checkouts', verbose_name=_('products'))
    watches = models.ManyToManyField(WatchModel, related_name='checkouts', verbose_name=_('watches'))
    mobile = models.ManyToManyField(MobilePhone, related_name='checkouts', verbose_name=_('mobile phones'))
    price = models.FloatField(null=True, verbose_name=_('price'))
    first_name = models.CharField(max_length=30, verbose_name=_('name'))
    last_name = models.CharField(max_length=30, verbose_name=_('second name'))
    phone = models.CharField(max_length=30, verbose_name=_('phone'))
    email = models.EmailField(verbose_name=_('email'))
    country = models.CharField(max_length=30, verbose_name=_('country'))
    company = models.CharField(max_length=75, verbose_name=_('company'))
    address1 = models.CharField(max_length=50, verbose_name=_('address'))
    city = models.CharField(max_length=30, verbose_name=_('city'))
    state = models.CharField(max_length=30, verbose_name=_('state'))
    postcode = models.CharField(max_length=30, verbose_name=_('postcode'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created_at'))

    def __str__(self):
        return str(f'{self.user} + {self.last_name}')

    class Meta:
        verbose_name = _('checkout')
        verbose_name_plural = _('checkouts')

contact/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

# Create your models here.


class ContactModel(models.Model):
    full_name = models.CharField(max_length=255, verbose_name=_('name'))
    email = models.EmailField(verbose_name=_('email'))
    subject = models.CharField(max_length=255, verbose_name=_('subject'))
    message = models.TextField(verbose_name=_('message'))
    created = models.DateTimeField(auto_now_add=True, verbose_name=_('created'))

    def __str__(self):
        return self.full_name

    class Meta:
        verbose_name = _('contact')
        verbose_name_plural = _('contacts')


class FaqModel(models.Model):
    title = models.CharField(max_length=255, verbose_name=_('title'))
    description = models.TextField(verbose_name=_('description'))

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _('faq')
        verbose_name_plural = _('faqs')

wishlist/models.py
from django.contrib.auth import get_user_model
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.utils.translation import gettext_lazy as _

UserModel = get_user_model()


class UserActivity(models.Model):
    liked_by = models.ForeignKey(UserModel, null=True, blank=True,
                                 related_name='likes',
                                 on_delete=models.CASCADE,
                                 verbose_name=_('liked_by'))
    created_at = models.DateTimeField(auto_now_add=True,
                                      verbose_name=_('created_at'))
    content_type = models.ForeignKey(ContentType,
                                     on_delete=models.CASCADE,
                                     related_name='likes')
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')

checkouts/forms.py
from django import forms


class CheckoutsModelForm(forms.ModelForm):
    class Meta:
        pass

contact/forms.py
from django import forms

from contact.models import ContactModel


class ContactModelForm(forms.ModelForm):
    class Meta:
        model = ContactModel
        exclude = ['created']

checkouts/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import TemplateView


class CheckoutTemplateView(TemplateView):
    template_name = 'checkout.html'


class CartTemplateView(TemplateView):
    template_name = 'shopping-cart.html'

contact/views.py
from django.shortcuts import render

# Create your views here.
from django.urls import reverse
from django.views.generic import CreateView, ListView

from contact.forms import ContactModelForm
from contact.models import FaqModel


class ContactCreateView(CreateView):
    template_name = 'contact.html'
    form_class = ContactModelForm

    def get_success_url(self):
        return reverse('contact:contact')


class FaqView(ListView):
    template_name = 'faq.html'

    def get_queryset(self):
        qs = FaqModel.objects.all()

        return qs

wishlist/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.contenttypes.models import ContentType
from django.shortcuts import redirect
from django.views.generic import ListView
from django.apps import apps
from wishlist.models import UserActivity


class WishListView(LoginRequiredMixin, ListView):
    template_name = 'wishlist.html'

    def get_queryset(self):
        return self.request.user.likes.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['content_type'] = UserActivity.objects.order_by('-pk')

        return context


@login_required
def add_wishlist(request, pk, klass):
    app, klass = klass.split('.')[0], klass.split('.')[-1]
    model = apps.get_model(app_label=app, model_name=klass)
    ct = ContentType.objects.get_for_model(model)
    user = request.user

    if UserActivity.objects.filter(liked_by=user, object_id=pk, content_type=ct).exists():
        UserActivity.objects.filter(liked_by=user, object_id=pk, content_type=ct).delete()
    else:
        UserActivity.objects.create(liked_by=user, object_id=pk, content_type=ct)

    return redirect(request.GET.get('next', '/'))

templates/blog-left-sidebar.html
{% extends 'layouts/base.html' %}

{% load i18n %}

{% load static %}

{% block content %}
    <div class="breadcrumb-area" xmlns="http://www.w3.org/1999/html">
        <div class="container">
            <div class="breadcrumb-content">
                <ul>
                    <li><a href="index.html">{% trans 'Home' %}</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="li-main-blog-page pt-60 pb-55">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 order-lg-1 order-2">
                    <div class="li-blog-sidebar-wrapper">
                        <div class="li-blog-sidebar">
                            <div class="li-sidebar-search-form">
                                <form action="#">
                                    <input name="q" type="text" class="li-search-field" placeholder="search here">
                                    <button type="submit" class="li-search-btn"><i class="fa fa-search"></i>
                                    </button>
                                </form>
                            </div>
                        </div>
                        <div class="li-blog-sidebar pt-25">
                            <h4 class="li-blog-sidebar-title">{% trans 'Categories' %}</h4>
                            <ul class="li-blog-archive">
                                {% for category in category %}
                                    <li><a {% if request.GET.category == category.pk|stringformat:'i' %}
                                        style="color: #00a9da"
                                    {% endif %} onclick="addUrlParameter('category', {{ category.pk }})"
                                        href="#" style="color: #0b0b0b">{{ category.title }}</a>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                        <div class="li-blog-sidebar">
                            <h4 class="li-blog-sidebar-title">{% trans 'Recent Post' %}</h4>
                            {% for blog in recent_post %}
                                <div class="li-recent-post pb-30">
                                    <div class="li-recent-post-thumb">
                                        <a href="{{ blog.video.url }}">
                                            <video class="img-full" src="{{ blog.video.url }}"
                                                   type="video/mp4"></video>
                                        </a>

                                    </div>
                                    <div class="li-recent-post-des">
                                        <span><a
                                                href="{% url 'blog:blog-detail' pk=blog.pk %}">{{ blog.title }}</a></span>
                                        <span class="li-post-date">{{ blog.created|date:'d.m.Y' }}</span>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                        <div class="li-blog-sidebar">
                            <h4 class="li-blog-sidebar-title">{% trans 'Tags' %}</h4>
                            <ul class="li-blog-tags">
                                {% for tag in tags %}
                                    <li>
                                        <a {% if request.GET.tag == tag.pk|stringformat:'i' %}
                                            style="color: #00a9da"
                                        {% endif %} href="#"
                                            onclick="addUrlParameter('tag', {{ tag.pk }})">{{ tag.title }}
                                        </a>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-lg-9 order-lg-2 order-1">
                    <div class="row li-main-content">
                        {% for blog in object_list %}
                            <div class="col-lg-6 col-md-6">
                                <div class="li-blog-single-item pb-25">
                                    <div class="li-blog-banner">
                                        <a href="{{ blog.video.url }}">
                                            <video class="img-full"
                                                   src="{{ blog.video.url }}" type="video/mp4"></video>
                                        </a>
                                    </div>
                                    <div class="li-blog-content">
                                        <div class="li-blog-details">
                                            <h3 class="li-blog-heading pt-25">
                                                <a href="{% url 'blog:blog-detail' pk=blog.pk %}">{{ blog.title }}</a>
                                            </h3>
                                            <div class="li-blog-meta">
                                                <a class="author" href="#"><i class="fa fa-user"></i>{{ blog.author }}
                                                </a>

                                                <a class="post-time" href="#"><i
                                                        class="fa fa-calendar"></i>{{ blog.created|date:'d.m.Y' }}</a>
                                            </div>
                                            <p>{{ blog.short_description|safe }}</p>
                                            <a class="read-more" href="{% url 'blog:blog-detail' pk=blog.pk %}">
                                                <strong style="color: #00a9da">{% trans 'Read More' %}</strong></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                        <div class="col-lg-12">
                            <div class="li-paginatoin-area text-center pt-25">
                                <div class="row">
                                    <div class="col-lg-12">
                                        <div class="pagination">
                                        <span class="step-links">
                                            {% if page_obj.has_previous %}
                                                <a href="?page=1">&laquo;{% trans 'First' %}</a>
                                                <a href="?page={{ page_obj.previous_page_number }}">{% trans 'Previous' %}</a>
                                            {% endif %}

                                            <span class="current">
                                                {% trans 'Page' %} {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                                            </span>

                                            {% if page_obj.has_next %}
                                                <a href="?page={{ page_obj.next_page_number }}">{% trans 'Next' %}</a>
                                                <a href="?page={{ page_obj.paginator.num_pages }}">{% trans 'Last ' %}&raquo;</a>
                                            {% endif %}
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block extra_js %}
    <script>
        function addUrlParameter(name, value) {
            let searchParams = new URLSearchParams(window.location.search)
            searchParams.set(name, value)
            window.location.search = searchParams.toString()
        }
    </script>
{% endblock %}

templates/mobile-phones.html
{% extends 'layouts/base.html' %}

{% load i18n %}

{% load static %}

{% load basic_tags %}

{% block extra_css %}
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/ion-rangeslider/2.3.1/css/ion.rangeSlider.min.css"/>
{% endblock %}



{% block content %}

    <div class="breadcrumb-area">
        <div class="container">
            <div class="breadcrumb-content">
                <ul>
                    <li><a href="index.html">{% trans 'Home' %}</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="content-wraper pt-60 pb-60 pt-sm-30">
        <div class="container">
            <div class="row">
                <div class="col-lg-9 order-1 order-lg-2">
                    <div class="single-banner shop-page-banner">
                        <a href="#">
                            <img src="{% static 'images/bg-banner/2.jpg' %}" alt="Li's Static Banner">
                        </a>
                    </div>
                    <div class="shop-top-bar mt-30">
                        <div class="shop-bar-inner">
                            <div class="product-view-mode">
                                <ul class="nav shop-item-filter-list" role="tablist">
                                    <li class="active" role="presentation">
                                        <a aria-selected="true" class="active show"
                                           data-toggle="tab" role="tab"
                                           aria-controls="grid-view"
                                           href="#grid-view"><i class="fa fa-th"></i>
                                        </a>
                                    </li>
                                    <li role="presentation"><a data-toggle="tab" role="tab"
                                                               aria-controls="list-view"
                                                               href="#"><i class="fa fa-th-list"></i></a>
                                    </li>
                                </ul>
                            </div>
                            <div class="toolbar-amount">
                                <span>Showing {{ page_obj.start_index }}-{{ page_obj.end_index }} of {{ page_obj.paginator.count }}</span>
                            </div>
                        </div>
                    </div>
                    <div class="shop-products-wrapper">
                        <div class="tab-content">
                            <div id="grid-view" class="tab-pane fade active show" role="tabpanel">
                                <div class="product-area shop-product-area">
                                    <div class="row">
                                        {% for phone in object_list %}
                                            <div class="col-lg-4 col-md-4 col-sm-6 mt-40">
                                                <div class="single-product-wrap">
                                                    <div class="product-image">
                                                        <a href="#">
                                                            <img src="{{ phone.image.url }}"
                                                                 alt="Li's Product Image">
                                                        </a>
                                                        <span class="sticker">{% trans 'New' %}</span>
                                                    </div>
                                                    <div class="product_desc">
                                                        <div class="product_desc_info">
                                                            <div class="product-review">
                                                                <h5 class="manufacturer">
                                                                    <a href="#">Graphic
                                                                        Corner</a>
                                                                </h5>
                                                                <div class="rating-box">
                                                                    <ul class="rating">
                                                                        <li><i class="fa fa-star-o"></i></li>
                                                                        <li><i class="fa fa-star-o"></i></li>
                                                                        <li><i class="fa fa-star-o"></i></li>
                                                                        <li class="no-star"><i class="fa fa-star-o"></i>
                                                                        </li>
                                                                        <li class="no-star"><i class="fa fa-star-o"></i>
                                                                        </li>
                                                                    </ul>
                                                                </div>
                                                            </div>
                                                            <h4><a class="product_name"
                                                                   href="{% url 'mobile:mobile-view' pk=phone.pk %}">{{ phone.title }}</a>
                                                            </h4>
                                                            <div class="price-box">
                                                                <span class="new-price">%{{ phone.get_price }}
                                                                    {% if phone.is_discount %}
                                                                        <strike class="small">${{ phone.price }}</strike>
                                                                    {% endif %}
                                                                </span>
                                                            </div>
                                                        </div>
                                                        <div class="add-actions">
                                                            <ul class="add-actions-link">
                                                                <li class="add-cart active"><a
                                                                        href="shopping-cart.html">{% trans 'Add to cart' %}</a></li>
                                                                <li class="fa fa-eye"> {{ phone.post_views }}</li>
                                                                <li><a class="links-details" href="{% url 'wishlist:add-wishlist' pk=phone.pk klass=phone|class_name %}?next={{ request.path }}?{{ request.GET.urlencode }}"><i
                                                                        class="fa fa-heart-o"></i></a></li>
                                                            </ul>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                            <div class="paginatoin-area" style="margin-top: 15%">
                                <div class="row">
                                    <div class="col-lg-6 col-md-6 pt-xs-15">
                                        <p>{% trans 'Hurry up to shopping Mobile Phones' %}</p>
                                    </div>
                                    <div class="pagination">
                                        <span class="step-links">
                                            {% if page_obj.has_previous %}
                                                <a href="?page=1">&laquo; {% trans 'First' %}</a>
                                                <a href="?page={{ page_obj.previous_page_number }}">{% trans 'Previous' %}</a>
                                            {% endif %}

                                            <span class="current">
                                                {% trans 'Page' %} {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                                            </span>

                                            {% if page_obj.has_next %}
                                                <a href="?page={{ page_obj.next_page_number }}">{% trans 'Next' %}</a>
                                                <a href="?page={{ page_obj.paginator.num_pages }}">{% trans 'Last' %} &raquo;</a>
                                            {% endif %}
                                            </span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 order-2 order-lg-1">
                    <div class="sidebar-categores-box">
                        <div class="sidebar-title">
                            <h2>{% trans 'Filter By' %}</h2>
                        </div>
                        <input type="text" class="js-range-slider" name="my_range" value=""/>
                        <a href="{% url 'mobile:mobile-list' %}">
                            <button class="btn-clear-all mb-sm-30 mb-xs-30">{% trans 'Clear all' %}</button>
                        </a>
                        <div class="filter-sub-area">
                            <h5 class="filter-sub-titel">{% trans 'Brand' %}</h5>
                            <ul>
                                {% for brand in brands %}
                                    <li><a {% if request.GET.brand == brand.pk|stringformat:'i' %}
                                        style="color: #00a9da"
                                    {% endif %} style="color: #0b0b0b" href="#"
                                        onclick="addUrlParameter('brand', {{ brand.pk }})">
                                        {{ brand.title }}
                                    </a>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                        <div class="filter-sub-area pt-sm-10 pt-xs-10">
                            <h5 class="filter-sub-titel">{% trans 'Categories' %}</h5>
                            <ul>
                                {% for category in categories %}
                                    <li>
                                        <a {% if request.GET.category == category.pk|stringformat:'i' %}
                                            style="color: #00a9da"
                                        {% endif %} style="color: #0b0b0b" href="#"
                                            onclick="addUrlParameter('category', {{ category.pk }})">
                                            {{ category.title }}
                                        </a>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                        <div class="filter-sub-area pt-sm-10 pt-xs-10">
                            <h5 class="filter-sub-titel">{% trans 'Color' %}</h5>
                            <div class="color-categoriy">
                                <ul>
                                    {% for color in colors %}
                                        <a href="#"
                                           onclick="addUrlParameter('color', {{ color.pk }})">
                                            <p style="width: 50%; border-radius: 50px; background-color: {{ color.code }}">
                                                &nbsp
                                            </p>
                                        </a>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block extra_js %}
    <script>
        function addUrlParameter(name, value) {
            let searchParams = new URLSearchParams(window.location.search)
            searchParams.set(name, value)
            window.location.search = searchParams.toString()
        }
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/ion-rangeslider/2.3.1/js/ion.rangeSlider.min.js"></script>

    <script>
        $(" .js-range-slider").ionRangeSlider({
            type: "double",
            grid: true,
            min: {{ min_price }},
            max: {{ max_price }},
            from: {% get_price_url request 0 %},
            to: {% get_price_url request 1 %},
            prefix: "$",
            onFinish(data) {
                let result = data.from.toString() + ';' + data.to.toString();
                addUrlParameter('price', result)
            }
        });
    </script>
{% endblock %}